add_executable_directory("${CMAKE_CURRENT_LIST_DIR}/executable_a")
add_executables_directory("${CMAKE_CURRENT_LIST_DIR}/executables")
add_library_directory("${CMAKE_CURRENT_LIST_DIR}/library_a")
add_libraries_directory("${CMAKE_CURRENT_LIST_DIR}/libraries")
add_tests_directory("${CMAKE_CURRENT_LIST_DIR}/test")
