foreach (TARGET_DIR ${EXTERN_DIRS})
    get_filename_component(TARGET_NAME "${TARGET_DIR}" NAME)
    block()
        set(BUILD_TESTING OFF)
        set(CMAKE_MESSAGE_LOG_LEVEL NOTICE)
        set(CMAKE_SUPPRESS_DEVELOPER_WARNINGS 1)
        set(CMAKE_WARN_DEPRECATED OFF)
        include("${TARGET_DIR}/extern.cmake")
    endblock()
    message("${PROJECT_NAME} - Added External Dependency  ${TARGET_NAME}")
endforeach ()
