include_guard(GLOBAL)

function(upper_snake_case OUT_VAR IN_VAR)
    set(${OUT_VAR} "${IN_VAR}")
    string(REGEX MATCH "[a-z]" "${${OUT_VAR}}" CONTAINS_LOWER)
    if (CONTAINS_LOWER)
        string(REGEX REPLACE "([A-Z])" "_\\1" ${OUT_VAR} "${${OUT_VAR}}")
    endif ()
    string(REGEX REPLACE "[^A-Za-z0-9]+" "_" ${OUT_VAR} "${${OUT_VAR}}")
    string(REGEX REPLACE "_+" "_" ${OUT_VAR} "${${OUT_VAR}}")
    string(REGEX REPLACE "^_+" "" ${OUT_VAR} "${${OUT_VAR}}")
    string(TOUPPER "${${OUT_VAR}}" ${OUT_VAR})
    set(${OUT_VAR} "${${OUT_VAR}}" PARENT_SCOPE)
endfunction()
