name: CMake

on:
  release:
    types: [ published ]
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build_type: Release
            c_compiler: cl
            cpp_compiler: cl
            generator: Ninja
          - os: windows-latest
            build_type: Release
            c_compiler: cl
            cpp_compiler: cl
            generator: "Visual Studio 17 2022"
          - os: ubuntu-latest
            build_type: Release
            c_compiler: gcc
            cpp_compiler: g++
            generator: Ninja
          - os: ubuntu-latest
            build_type: Release
            c_compiler: clang
            cpp_compiler: clang++
            generator: Ninja

    steps:
      - uses: actions/checkout@v4
      - uses: ashutoshvarma/setup-ninja@master
        if: matrix.generator == 'Ninja'
      - uses: microsoft/setup-msbuild@v2
        if: matrix.os == 'windows-latest' && matrix.generator == 'Ninja'

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake
          -B "${{ steps.strings.outputs.build-output-dir }}"
          -S "${{ github.workspace }}"
          -G "${{ matrix.generator }}"
          -DCLANG_TIDY_TARGET=ON
          -DCLANG_FORMAT_TARGET=ON
          -DBUILD_TESTING=ON
          -DCMAKE_CXX_COMPILER="${{ matrix.cpp_compiler }}"
          -DCMAKE_C_COMPILER="${{ matrix.c_compiler }}"
          -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}"
          -DCMAKE_INSTALL_PREFIX="${{ steps.strings.outputs.build-output-dir }}/install"

      - name: Build
        run: |
          cmake --build "${{ steps.strings.outputs.build-output-dir }}" --config "${{ matrix.build_type }}"

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: |
          ctest --build-config "${{ matrix.build_type }}"

      - name: Install
        run: |
          cmake --install "${{ steps.strings.outputs.build-output-dir }}" --config "${{ matrix.build_type }}"
